name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  node-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install (no dependencies needed, but keep for future)
        run: npm ci || npm i

      - name: Run tests
        run: npm test
